# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Capstone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Capstone
  pod "SnapKit",'~> 4.0.0'

  pod "Material"
  # for DB
  pod 'RealmSwift', '~> 3.12.0'

  pod 'ReactiveCocoa'

  pod 'ZJTableViewManager'
  pod 'RETableViewManager'
  pod 'Canvas+'
  pod 'Alamofire'
  pod 'AlamofireImage'



  target 'CapstoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapstoneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
